# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"github" = ""
"robo3t" = ""
"rdm" = ""
"code" = ""
"google" = ""
"jenkins" = ""
"private browsing" = ""
"firefox" = ""
"chrome" = ""
"file manager" = ""
"nvim" = ""
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
"intellij" = ""
"settings" = ""
"steam" = " "
[other]
"fallback_icon" = "🗖"
deduplicate_icons = false
